on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  get-version-information:
    name: Get Version Information
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.split-version.outputs._1 }}
    steps:
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.ref }}
          seperator: '/'
      - uses: jungwinter/split@v1
        id: split-version
        with:
          msg: ${{ steps.split.outputs._2 }}
          seperator: '-'
  perform-release:
    name: Perform Release
    runs-on: ubuntu-20.04
    needs: get-version-information
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          LITANI_VERSION: ${{ needs.get-version-information.outputs.version }}
        with:
          tag_name: litani-${{ env.LITANI_VERSION }}
          release_name: litani-${{ env.LITANI_VERSION }}
          body: |
            This is LITANI version ${{ env.LITANI_VERSION }}.

            ## MacOS

            On MacOS, install Litani using [Homebrew](https://brew.sh/) with

            ```sh
            brew tap aws/tap
            brew install litani
            ```

            or upgrade (if it's already been installed) with:

            ```sh
            brew upgrade litani
            ```

            ## Ubuntu

            On Ubuntu, install LITANI by downloading the *.deb package below for Ubuntu 20 and install with

            ```sh
            # Ubuntu 20:
            $ dpkg -i litani-${{ env.LITANI_VERSION }}-Linux.deb
            ```
          draft: false
          prerelease: false
